services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - back
    env_file:
      - .env
    secrets:
      - db_user
      - db_pass
      - root_pass
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - front
      - back
    env_file:
      - .env
    secrets:
      - db_user
      - db_pass
      - wp_user_pass
      - wp_admin_user
      - wp_admin_pass
    restart: always
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - front
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none
  
  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress"
      o: bind
      type: none

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  db_user:
    file: ../secrets/db_user
  db_pass:
    file: ../secrets/db_pass
  root_pass:
    file: ../secrets/root_pass
  wp_user_pass:
    file: ../secrets/wp_user_pass
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
