services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none